version: '3.4'

services:
  simplenerapi:
    image: simplenerapi
    build:
      context: .
      dockerfile: ./docker/prod/core.Dockerfile
    ports:
      - 8000:8000
    volumes:
        - ./:/app
  db:
    env_file: .env
    build: 
      context: .
      dockerfile: ./docker/prod/mysql.Dockerfile
      args:
        MYSQL_USER: ${MYSQL_USER:-}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DB:-}
    restart: always
    ports:
      - "3306:3306"
