version: '3.4'

services:
  simplenerapi:
    image: simplenerapi
    build:
      context: .
      dockerfile: ./docker/dev/core.Dockerfile
    ports:
      - 8000:8000
    volumes:
        - ./:/app
    links:
      - "db:database"
    depends_on:
      - db
  db:
    env_file: .env
    build: 
      context: .
      dockerfile: ./docker/dev/mysql.Dockerfile
      args:
        MYSQL_USER: ${MYSQL_USER:-}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DB:-}
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

    ports:
      - "${MYSQL_PORT}:3306"